type PortfolioItem @table @unique(fields: ["ticker", "assetType"]) {
  ticker: String!
  assetType: String!
  quantity: Float!
  costBasis: Float!
  lastUpdated: Timestamp!
}

type Transaction @table {
  portfolioItem: PortfolioItem!
  type: String!
  quantity: Float!
  price: Float!
  date: Timestamp!
  useCash: Boolean!
}
